// Mocks generated by Mockito 5.4.6 from annotations
// in echomirror/test/features/auth/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:echomirror/core/services/serverpod_client_service.dart' as _i4;
import 'package:echomirror_server_client/echomirror_server_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _i3;
import 'package:shared_preferences/shared_preferences.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEndpointCaller_1 extends _i1.SmartFake
    implements _i2.EndpointCaller {
  _FakeEndpointCaller_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeServerpodClientShared_2 extends _i1.SmartFake
    implements _i2.ServerpodClientShared {
  _FakeServerpodClientShared_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSuccess_3 extends _i1.SmartFake implements _i3.AuthSuccess {
  _FakeAuthSuccess_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUuidValue_4 extends _i1.SmartFake implements _i2.UuidValue {
  _FakeUuidValue_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ServerpodClientService].
///
/// See the documentation for Mockito's code generation for more information.
class MockServerpodClientService extends _i1.Mock
    implements _i4.ServerpodClientService {
  MockServerpodClientService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i6.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i5.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [AuthenticationKeyManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationKeyManager extends _i1.Mock
    implements _i2.AuthenticationKeyManager {
  MockAuthenticationKeyManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> get authHeaderValue =>
      (super.noSuchMethod(
            Invocation.getter(#authHeaderValue),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<void> put(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#put, [key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> remove() =>
      (super.noSuchMethod(
            Invocation.method(#remove, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getHeaderValue() =>
      (super.noSuchMethod(
            Invocation.method(#getHeaderValue, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> toHeaderValue(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#toHeaderValue, [key]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);
}

/// A class which mocks [EndpointEmailIdp].
///
/// See the documentation for Mockito's code generation for more information.
class MockEndpointEmailIdp extends _i1.Mock implements _i2.EndpointEmailIdp {
  MockEndpointEmailIdp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  _i2.EndpointCaller get caller =>
      (super.noSuchMethod(
            Invocation.getter(#caller),
            returnValue: _FakeEndpointCaller_1(
              this,
              Invocation.getter(#caller),
            ),
          )
          as _i2.EndpointCaller);

  @override
  _i2.ServerpodClientShared get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeServerpodClientShared_2(
              this,
              Invocation.getter(#client),
            ),
          )
          as _i2.ServerpodClientShared);

  @override
  _i5.Stream<_i2.SerializableModel> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i5.Stream<_i2.SerializableModel>.empty(),
          )
          as _i5.Stream<_i2.SerializableModel>);

  @override
  set client(_i2.ServerpodClientShared? _client) => super.noSuchMethod(
    Invocation.setter(#client, _client),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.AuthSuccess> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i5.Future<_i3.AuthSuccess>.value(
              _FakeAuthSuccess_3(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthSuccess>);

  @override
  _i5.Future<_i2.UuidValue> startRegistration({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#startRegistration, [], {#email: email}),
            returnValue: _i5.Future<_i2.UuidValue>.value(
              _FakeUuidValue_4(
                this,
                Invocation.method(#startRegistration, [], {#email: email}),
              ),
            ),
          )
          as _i5.Future<_i2.UuidValue>);

  @override
  _i5.Future<String> verifyRegistrationCode({
    required _i2.UuidValue? accountRequestId,
    required String? verificationCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyRegistrationCode, [], {
              #accountRequestId: accountRequestId,
              #verificationCode: verificationCode,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#verifyRegistrationCode, [], {
                  #accountRequestId: accountRequestId,
                  #verificationCode: verificationCode,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.AuthSuccess> finishRegistration({
    required String? registrationToken,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishRegistration, [], {
              #registrationToken: registrationToken,
              #password: password,
            }),
            returnValue: _i5.Future<_i3.AuthSuccess>.value(
              _FakeAuthSuccess_3(
                this,
                Invocation.method(#finishRegistration, [], {
                  #registrationToken: registrationToken,
                  #password: password,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.AuthSuccess>);

  @override
  _i5.Future<_i2.UuidValue> startPasswordReset({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#startPasswordReset, [], {#email: email}),
            returnValue: _i5.Future<_i2.UuidValue>.value(
              _FakeUuidValue_4(
                this,
                Invocation.method(#startPasswordReset, [], {#email: email}),
              ),
            ),
          )
          as _i5.Future<_i2.UuidValue>);

  @override
  _i5.Future<String> verifyPasswordResetCode({
    required _i2.UuidValue? passwordResetRequestId,
    required String? verificationCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPasswordResetCode, [], {
              #passwordResetRequestId: passwordResetRequestId,
              #verificationCode: verificationCode,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#verifyPasswordResetCode, [], {
                  #passwordResetRequestId: passwordResetRequestId,
                  #verificationCode: verificationCode,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> finishPasswordReset({
    required String? finishPasswordResetToken,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#finishPasswordReset, [], {
              #finishPasswordResetToken: finishPasswordResetToken,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasAccount() =>
      (super.noSuchMethod(
            Invocation.method(#hasAccount, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> sendStreamMessage(_i2.SerializableModel? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendStreamMessage, [message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void resetStream() => super.noSuchMethod(
    Invocation.method(#resetStream, []),
    returnValueForMissingStub: null,
  );
}
